name: Deploy Auth Service to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "Project-Code/backend-microservice/apps/auth/**"
      - ".github/workflows/deploy-auth-service.yaml"

jobs:
  build-and-push:
    name: Build & Push Auth Service Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Running command
        run: |
            ls

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@v6
    #     with:
    #       context: ./auth-service
    #       file: ./auth-service/Dockerfile
    #       push: true
    #       tags: |
    #         ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
    #         ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
